### ISSUE TITLE
Can I translate this game and how I can do this?

### ISSUE THREAD

**Issue by Filipp-Druan** [jaredkrinke/sic1#456]
Hello! Can I translate your game? If yes, where can I find the text content?

**Comment by jaredkrinke** [comment]
Unfortunately, I didn't architect the game with translations in mind--there are just hard-coded strings all over the place.

Do you have any suggestions on tools for translating browser-based games (specifically Preact--although I could potentially switch to React)? Have you worked with any such tools/libraries, especially related to web apps?

Note: I'm tracking improvements in this bug: #307

**Comment by jaredkrinke** [comment]
I'm starting to answer the second part of your question (location of the text content) here: https://github.com/jaredkrinke/sic1/issues/457

Obviously, it will be best for me to consolidate all those resources into a single location--but first I have to find them!

**Comment by jaredkrinke** [comment]
@Filipp-Druan do you think [Creative Commons Attribution, Share-Alike](https://creativecommons.org/licenses/by-sa/4.0/) is a reasonable license for the translations?

**Comment by jaredkrinke** [comment]
@Filipp-Druan Which language were you interested in?

You're under no obligation to translate anything, but if you were going to, would you prefer to work over CrowdIn (a translation management system) or directly via GitHub (using ICU message format in JSON)?

I'm testing out CrowdIn for SIC-1 here: https://crowdin.com/project/sic-1

**Comment by jaredkrinke** [comment]
Closing this since the game can now be translated. Feel free to ask any further questions within this issue, thanks!
